apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o8yrn089y-go 
  janus-idp.io/tekton: o8yrn089y-go
  backstage.io/kubernetes-id: o8yrn089y-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o8yrn089y-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml